Repository digitalocean/do-markdownit, pull requests merged in 2023-10, with the labels that each got.

#84 Enable client-side Prism in dev playground
  dev/client.js
Labels: documentation

#83 Update color palette to match new design system
  CHANGELOG.md
  styles/_callouts.scss
  styles/_code.scss
  styles/_code_label.scss
  styles/_code_prism.scss
  styles/_code_secondary_label.scss
  styles/_highlight.scss
  styles/_mixins.scss
  styles/_theme.scss
  styles/_typography.scss
  styles/digitalocean/_callouts.scss
  styles/digitalocean/_code_environments.scss
Labels: enhancement, minor

#85 Release v1.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: minor, release

#87 Add border stroke to code block
  CHANGELOG.md
  styles/_code.scss
Labels: enhancement, minor

#88 Release v1.12.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: minor, release
