Repository digitalocean/do-markdownit, pull requests merged in 2023-03, with the labels that each got.

#50 Dependency updates
  .nvmrc
  CHANGELOG.md
  package-lock.json
  package.json
Labels: patch, dependencies

#51 Release v1.5.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: patch, release

#54 Add vimeo embed
  CHANGELOG.md
  README.md
  fixtures/full-input.md
  fixtures/full-output.html
  index.js
  rules/embeds/vimeo.js
  rules/embeds/vimeo.test.js
  styles/_vimeo.scss
  styles/index.scss
Labels: enhancement, minor

#55 Add Instagram plugin
  CHANGELOG.md
  README.md
  fixtures/full-input.md
  fixtures/full-output.html
  index.js
  rules/embeds/instagram.js
  rules/embeds/instagram.test.js
  styles/_instagram.scss
  styles/index.scss
Labels: enhancement, minor

#57 Add slideshow plugin
  CHANGELOG.md
  README.md
  fixtures/full-input.md
  fixtures/full-output.html
  index.js
  rules/embeds/slideshow.js
  rules/embeds/slideshow.test.js
  styles/_slideshow.scss
  styles/index.scss
Labels: enhancement, minor

#58 Add limit_tokens plugin
  CHANGELOG.md
  README.md
  index.js
  rules/image_caption.js
  rules/limit_tokens.js
  rules/limit_tokens.test.js
Labels: enhancement, minor

#59 Release v1.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: minor, release
