Repository digitalocean/do-markdownit, pull requests merged in 2024-05, with the labels that each got.

#108 Add plugin to set attributes on links
  CHANGELOG.md
  README.md
  index.js
  modifiers/link_attributes.js
  modifiers/link_attributes.test.js
Labels: enhancement, minor

#109 Dependency updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: patch, dependencies

#110 Release v1.13.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: minor, release

#111 Set --skipLibCheck for tsc
  package.json
Labels: bug

#112 Use shared toolbar for code block label + buttons
  CHANGELOG.md
  README.md
  fixtures/full-output.html
  modifiers/fence_label.js
  modifiers/fence_label.test.js
  modifiers/prismjs.test.js
  styles/_code_label.scss
  styles/_code_prism.scss
  styles/digitalocean/_code_environments.scss
Labels: enhancement, minor

#114 Fix repository URL in package.json
  package.json
Labels: bug

#113 Release v1.14.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: minor, release
