Repository digitalocean/do-markdownit, pull requests merged in 2024-03, with the labels that each got.

#96 Align code-block line numbers to the right
  CHANGELOG.md
  styles/_code_prefix.scss
Labels: bug, patch

#97 Update PUBLISH + CHANGELOG instructions for new versions
  CHANGELOG.md
  PUBLISH.md
Labels: documentation

#98 Release v1.12.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: patch, release

#100 Dependency updates
  .nvmrc
  CHANGELOG.md
  package-lock.json
  package.json
Labels: patch, dependencies

#101 Release v1.12.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: patch, release

#103 Fix inline code styling when in a link
  CHANGELOG.md
  fixtures/full-input.md
  fixtures/full-output.html
  styles/_code.scss
  styles/_code_prism.scss
  styles/_typography.scss
Labels: bug, patch

#104 Release v1.12.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: patch, release
